Environment activated
/home/tsw96d/.conda/envs/YOLO/bin/python
Python 3.11.10
CUDA available: True
CUDA device count: 2
CUDA current device: 0
CUDA device name: Tesla V100-SXM2-32GB
Traceback (most recent call last):
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/test.py", line 5, in <module>
    model = YOLO("./ultralytics/cfg/models/v8/yolo11.yaml")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/engine/model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/engine/model.py", line 248, in _new
    cfg_dict = yaml_model_load(cfg)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/nn/tasks.py", line 1124, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
                                                        ^^^^^^^^^^^^^^^^
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/utils/checks.py", line 525, in check_yaml
    return check_file(file, suffix, hard=hard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/ultralytics/utils/checks.py", line 517, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'ultralytics/cfg/models/v8/yolo11.yaml' does not exist
